force-app/main/default/objects/Case/fields/A_Number__c.field-meta.xml
<CustomField>
    <fullName>A_Number__c</fullName>
    <description>A File Number</description>
    <label>A Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/File_Pulled_for_Processing__c.field-meta.xml
<CustomField>
    <fullName>File_Pulled_for_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Pulled for Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/barcodeReaderHelper.cls
public with sharing class barcodeReaderHelper {

    @AuraEnabled
    public static String getCaseId(String aNumber){
        List<Case> theCaseId = [Select Id, Status, File_Pulled_for_Processing__c from Case WHERE A_Number__c = :aNumber AND Status != 'Closed'];

        if(theCaseId.size() > 0){

            Case thisCase = theCaseId[0];
            //If Case is in File Processing, Mark it as pulled and re-assign owner.
            if (thisCase.Status == 'File_Processing'){
                //If not already marked as pulled, mark it

                if (thisCase.File_Pulled_for_Processing__c != true){
                    thisCase.File_Pulled_for_Processing__c = true;
                }

                if (thisCase.File_Pulled_for_Processing__c != true){
                    thisCase.File_Pulled_for_Processing__c = true;
                }

                thisCase.OwnerId = UserInfo.getUserId();
                update thisCase;
            }

            return (String)thisCase.Id;
        }

        return null;
    }
}