force-app/main/default/objects/Case/fields/A_Number__c.field-meta.xml
<CustomField>
    <fullName>A_Number__c</fullName>
    <description>A File Number</description>
    <label>A Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_File_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Date_File_Delivered__c</fullName>
    <label>Date File Delivered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_File_Processed__c.field-meta.xml
<CustomField>
    <fullName>Date_File_Processed__c</fullName>
    <label>Date File Processed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_File_Pulled_for_Processing__c.field-meta.xml
<CustomField>
    <fullName>Date_File_Pulled_for_Processing__c</fullName>
    <label>Date File Pulled for Processing</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_File_Pulled_from_Shelf__c.field-meta.xml
<CustomField>
    <fullName>Date_File_Pulled_from_Shelf__c</fullName>
    <label>Date File Pulled from Shelf</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/File_Delivered__c.field-meta.xml
<CustomField>
    <fullName>File_Delivered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Delivered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/File_Processed__c.field-meta.xml
<CustomField>
    <fullName>File_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/File_Pulled_for_Processing__c.field-meta.xml
<CustomField>
    <fullName>File_Pulled_for_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Pulled for Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/File_Pulled_from_Shelf__c.field-meta.xml
<CustomField>
    <fullName>File_Pulled_from_Shelf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Pulled from Shelf</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RailsRecordPageWidgetHelper.cls
public inherited sharing class RailsRecordPageWidgetHelper {
    public RailsRecordPageWidgetHelper() {

    }


    @AuraEnabled
    public static MobileCase getMobileCase(String recordId){
        List<Case> myCases = [SELECT Id, Status, ContactId, AccountId, OwnerId, A_Number__c, Owner.Name, Owner.FirstName, Owner.LastName, File_Pulled_from_Shelf__c, Date_File_Pulled_from_Shelf__c,  File_Delivered__c, Date_File_Delivered__c, File_Pulled_for_Processing__c, Date_File_Pulled_for_Processing__c, File_Processed__c, Date_File_Processed__c FROM Case WHERE Id = :recordId];
        MobileCase mobileCase = new MobileCase();

        if(myCases.size() > 0){
                Case thisCase = myCases[0];
                List<RailsRecord> railsRecord = (List<RailsRecord>)System.JSON.deserialize(eWRTSApiHelper.RAILSSearch(thisCase.A_Number__c), List<RailsRecord>.class);

                mobileCase.railsRecord = railsRecord[0];
                mobileCase.caseRecord = thisCase;
                mobileCase.anumber = thisCase.A_Number__c;
                mobileCase.accordianTitle = thisCase.A_Number__c + ' - ' + railsRecord[0].location_room + ' - ' + railsRecord[0].location_shelf;
        }
        System.debug(System.JSON.serialize(mobileCase));
        return mobileCase;
    }


}